spring:
  application:
    name: demo-spring-boot-jwt
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/init_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

jwt:
  private:
    url: "/private/**"
  type: "Bearer "
  secret: myTestSecretKeyMyTestSecretKeyMyTestSecretKeyMyTestSecretKeyMyTestSecretKey
  tokenExpiration: 1m
  refreshTokenExpiration: 10m
server:
  port: 8081
springdoc:
  swagger-ui:
    path: "/public/swagger-ui.html"

logging:
  level:
    org:
      springframework:
        security: INFO
